### ISSUE TITLE
Отражение шариков

### ISSUE THREAD

**Issue by avasyukov** [vladahub/task2#11]
Фиксирую: на семинаре допилить не вышло.

При столкновении большого и маленького шарика маленький как будто проходит внутрь большого, после чего отражается от чего-то похожего на его центр (но это не точно).

Есть подозрение, что проблема чисто в коде, который считает скорости при ударе (но это тоже не точно).

**Comment by avasyukov** [comment]
Проблему с радиусами починили.

Для вот такого входа:
```
2
0 0 10 0 0
-50 0 1 1 0
```
Всё вполне мило. Вот так - https://youtu.be/1cZC_uB9340

Но для вот такого входа:
```
2
0 0 10 0 0
0 -25 1 0 1
```
Всё уже не так мило - https://youtu.be/kYjjNJoD5_w - оно просто стоит на месте. Моё мнение - где-то по дороге протеряли скорость по игреку.

**Comment by yokomeow** [comment]
![59](https://user-images.githubusercontent.com/32332255/40484219-7e96f502-5f63-11e8-99de-996275bda3b0.png)

Я запустила с таким входом, где не двигаются шарики, и вот что получилось.
Судя по второму числу (игриковая координата маленького шарика), он двигается, но очень медленно. Я проверю еще скорости, но, вроде, все работает.

**Comment by avasyukov** [comment]
Ок, тоже проверю контрольно.

**Comment by avasyukov** [comment]
Мой косяк, стенки плохо стояли. Закрываем тикет.
